import type { PracticeProblem } from '../../problemTypes';
import loopJavascriptSolution from './solutions/loop.js?raw';
import loopTypescriptSolution from './solutions/loop.ts?raw';
import reduceJavascriptSolution from './solutions/reduce.js?raw';
import reduceTypescriptSolution from './solutions/reduce.ts?raw';

export const countByProblem: PracticeProblem = {
  id: 'countBy',
  title: 'Count By',
  difficulty: 'Medium',
  description:
    'Implement `countBy(array, iteratee)`, which creates an object composed of keys generated by running each element of `array` through `iteratee`. The value for each key should be the number of times that key was returned.\n\nThe `iteratee` function is called with one argument, the current value. If the array is empty, return an empty object. Keys such as `null` and `undefined` should be counted using normal JavaScript object property behavior.\n\nExamples:\n`countBy([6.1, 4.2, 6.3], Math.floor)` returns `{ 4: 1, 6: 2 }`.\n`countBy([{ n: 3 }, { n: 5 }, { n: 3 }], (o) => o.n)` returns `{ 3: 2, 5: 1 }`.\n`countBy([{ n: 1 }, { n: 2 }], (o) => o.m)` returns `{ undefined: 2 }`.',
  points: [
    '`array` (Array): The array to iterate over.',
    '`iteratee` (Function): Called with each array value to produce a grouping key.',
    'Increment the count for each key returned by `iteratee`.',
    'Return `{}` when the input array is empty.',
    'Treat `null` and `undefined` keys according to normal object property coercion.',
    '(Object): Returns an object mapping generated keys to counts.',
  ],
  solutions: [
    {
      title: 'Loop',
      javascript: loopJavascriptSolution.trim(),
      typescript: loopTypescriptSolution.trim(),
    },
    {
      title: 'Reduce',
      javascript: reduceJavascriptSolution.trim(),
      typescript: reduceTypescriptSolution.trim(),
    },
  ],
};
